language: php
dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm

matrix:
  include:
    - php: 5.3
      dist: precise
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 5.3
    - php: 5.4
    - php: 5.5

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php ./composer.phar install --dev --prefer-source

script: php vendor/bin/phpunit --configuration phpunit.xml.dist
