language: php
os: linux
dist: xenial

jobs:
  include:
    - php: 7.2
      env: VERSIONS=--prefer-lowest
    - php: 7.3
    - php: 7.4
      env: COLLECT_COVERAGE=true

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - travis_retry composer update $VERSIONS

script:
  - vendor/bin/phpunit --coverage-text
